export const categories = {
  beverages: [
    "drinks",
    "coffee_and_creamer",
    "energy_drinks",
    "water",
    "soft_drinks",
    "powdered_drinks",
    "other_beverages",
  ],
  cigarettes_and_liquor: ["cigarettes", "liquor"],
  frozen_goods: ["ice", "meat", "poultry", "seafood", "other_frozen_goods"],
  canned_goods: ["canned_goods"],
  kitchen_essentials: [
    "condiments",
    "cooking_oil",
    "noodles",
    "rice",
    "spices",
    "other_kitchen_essentials",
  ],
  personal_care: [
    "diapers",
    "alcohol",
    "feminine_hygiene",
    "soap",
    "shampoo_and_conditioner",
    "other_personal_care",
  ],
  snacks: [
    "biscuits_and_crackers",
    "candies_lollipops_gums_and_other_chewables",
    "chips_and_nuts",
    "cup_noodles",
    "pastries",
    "other_snacks",
  ],
  others: ["others"],
};